function Get-AbrADSiteReplication {
    <#
    .SYNOPSIS
    Used by As Built Report to retrieve Microsoft AD Domain Sites Replication information.
    .DESCRIPTION

    .NOTES
        Version:        0.2.0
        Author:         Jonathan Colon
        Twitter:        @jcolonfzenpr
        Github:         rebelinux
    .EXAMPLE

    .LINK

    #>
    [CmdletBinding()]
    param (
        [Parameter (
            Position = 0,
            Mandatory)]
            [string]
            $Domain
    )

    begin {
        Write-PscriboMessage "Collecting AD Domain Sites Replication information."
    }

    process {
        Write-PscriboMessage "Collecting AD Domain Sites Replication Summary."
        Section -Style Heading4 'Site Replication Summary' {
            Paragraph "The following section provides a summary of the Active Directory Site Replication information."
            BlankLine
            $OutObj = @()
            if ($Domain) {
                foreach ($Item in $Domain) {
                    try {
                        $DCs =  Get-ADDomain -Identity $Item | Select-Object -ExpandProperty ReplicaDirectoryServers
                        foreach ($DC in $DCs) {
                            $Replication = Get-ADReplicationConnection -Server $DC -Properties *
                            foreach ($Repl in $Replication) {
                                $inObj = [ordered] @{
                                    'DC Name' = $DC
                                    'Description' = $Repl.Description
                                    'Replicate From Directory Server' = $Repl.ReplicateFromDirectoryServer
                                    'Replicate To Directory Server' = $DC
                                    'Replicated Naming Contexts' = $Repl.ReplicatedNamingContexts
                                    'Transport Protocol' = $Repl.InterSiteTransportProtocol
                                    'AutoGenerated' = ConvertTo-TextYN $Repl.AutoGenerated
                                    'Enabled' = ConvertTo-TextYN $Repl.enabledConnection
                                    'Created' = ($Repl.Created).ToUniversalTime().toString("r")
                                }
                            }
                            $OutObj += [pscustomobject]$inobj
                        }
                    }
                    catch {
                        Write-Verbose "WARNING: Could not connect to DC $DC"
                    }

                }

                if ($HealthCheck.Site.Replication) {
                    $OutObj | Where-Object { $_.'Enabled' -ne 'Yes'} | Set-Style -Style Warning -Property 'Enabled'
                }

                $TableParams = @{
                    Name = "Site Replication Information - $($Domain.ToString().ToUpper())"
                    List = $true
                    ColumnWidths = 40, 60
                }
                if ($Report.ShowTableCaptions) {
                    $TableParams['Caption'] = "- $($TableParams.Name)"
                }
                $OutObj | Table @TableParams
            }
        }
        Write-PscriboMessage "Collecting AD Domain Sites Replication Failure Summary."
        Section -Style Heading4 'Site Replication Failure Summary' {
            Paragraph "The following section provides a summary of the Active Directory Site Replication Failure information."
            BlankLine
            $OutObj = @()
            if (($HealthCheck.Site.Replication) -and (Get-ADReplicationFailure -Target $Domain -Scope Domain)) {
                foreach ($Item in $Domain) {
                    $Failures =  Get-ADReplicationFailure -Target $Domain -Scope Domain
                    foreach ($Fails in $Failures) {
                            $inObj = [ordered] @{
                                'Server Name' = $Fails.Server
                                'Partner' = $Fails.Partner
                                'Last Error' = $Fails.LastError
                                'Failure Type' =  $Fails.FailureType
                                'Failure Count' = $Fails.FailureCount
                                'First Failure Time' = ($Fails.FirstFailureTime).ToUniversalTime().toString("r")
                            }
                        $OutObj += [pscustomobject]$inobj
                    }
                }

                if ($HealthCheck.Site.Replication) {
                    $OutObj | Where-Object {$NULL -notlike $_.'Last Error'} | Set-Style -Style Warning -Property 'Last Error', 'Failure Type', 'Failure Count', 'First Failure Time'
                }

                $TableParams = @{
                    Name = "Site Replication Failure Information - $($Domain.ToString().ToUpper())"
                    List = $true
                    ColumnWidths = 40, 60
                }
                if ($Report.ShowTableCaptions) {
                    $TableParams['Caption'] = "- $($TableParams.Name)"
                }
                $OutObj | Table @TableParams
            }
        }
    }

    end {}

}