name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - rebelinux
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report :)
        - Kindly **DO NOT** ask for instructions.
        - Use [Discussions](https://github.com/orgs/AsBuiltReport/discussions) section if you have a query or doubts or any other relevant question.
        - You may join [Slack community](https://the-code-community.slack.com#asbuiltreport) to interact with fellow contributors and users
        - Read project's [Web Site](https://www.asbuiltreport.com/user-guide/installation/) for detailed documentation.
        - Read project's [FAQs](https://www.asbuiltreport.com/support/faq/) section for Frequently asked questions.
        - Search for previous [Issues](https://github.com/AsBuiltReport/AsBuiltReport.NetApp.ONTAP/issues)/[Pull Requests](https://github.com/AsBuiltReport/AsBuiltReport.NetApp.ONTAP/pulls) if this issue is already reported or fix has been created.
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: >-
        Please provide a clear and concise description of the bug.
    validations:
      required: true
  - type: input
    id: command-line-input
    attributes:
      label: Command-line input
      description: >-
        Please provide the command line input you are using to run AsBuiltReport. Please ensure that you obscure any sensitive information.
      placeholder: New-AsBuiltReport -Report Microsoft.AD -Target xxxxxxx -Format Word,HTML -OutputFolderPath .\Documents\ -AsBuiltConfigFilePath .\AsBuiltReport\AsBuiltReport.json -ReportConfigFilePath .\AsBuiltReport\AsBuiltReport.Microsoft.AD.json -EnableHealthCheck -Verbose
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: >-
        Please provide a detailed list of steps to reproduce the bug.
      placeholder: |-
        1. ....
        2. ....
        3. ....
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: >-
        Please provide a clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: >-
        Please attach any screenshots to help explain the problem.  Please ensure that you obscure any sensitive information.
      placeholder: |-
        Drag and drop screenshots here.
  - type: textarea
    id: operating-system
    attributes:
      label: Operating System
      description: Please provide information about the operating system are you using.
      placeholder: macOS Big Sur, Windows 10, Ubuntu 20.04 LTS
    validations:
      required: true
  - type: textarea
    id: powershell-version
    attributes:
      label: PowerShell Version
      description: Please provide information about the PowerShell version you are using. Please provide the output from the following PowerShell command `$PSVersionTable`.
      placeholder: $PSVersionTable
    validations:
      required: true
  - type: textarea
    id: powershell-modules
    attributes:
      label: PowerShell Modules
      description: Please provide information about the PowerShell modules are you using. Please provide the output from the following PowerShell command `Get-Module -ListAvailable @("AsBuiltReport.Core";"AsBuiltReport.Microsoft.AD";"PSPKI";"PScriboCharts";"PScribo") | Select Name, Version`
      placeholder: Get-Module -ListAvailable @("AsBuiltReport.Core";"AsBuiltReport.Microsoft.AD";"PSPKI";"PScriboCharts";"PScribo") | Select Name, Version
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: This field is optional. You may provide additional context for the bug you wish to report. You may wish to include links to any related [issues](https://github.com/AsBuiltReport/AsBuiltReport.Microsoft.AD/issues) or other relevant information.
  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      description: >-
        Please ensure your bug report fulfills all of the following requirements.
        If you are unsure of what a specific requirement means, please follow the links to learn about it and understand why it is necessary before submitting.
      options:
        - label: >-
            I have read and followed the [bug reporting guidelines](https://www.asbuiltreport.com/about/contributing/#reporting-issues-and-bugs).
          required: true
