name: Change Request
description: Request a new change or an improvement
title: "[Change Request]: "
labels: ["change request"]
assignees:
  - rebelinux
body:
 - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this enahancement form :)
        - Kindly **DO NOT** ask for instructions.
        - Use [Discussions](https://github.com/orgs/AsBuiltReport/discussions) section if you have a query or doubts or any other relevant question.
        - You may join [Slack community](https://the-code-community.slack.com#asbuiltreport) to interact with fellow contributors and users
        - Read project's [Web Site](https://www.asbuiltreport.com/user-guide/installation/) for detailed documentation.
        - Read project's [FAQs](https://www.asbuiltreport.com/support/faq/) section for Frequently asked questions.
        - Search for previous [Issues](https://github.com/AsBuiltReport/AsBuiltReport.NetApp.ONTAP/issues)/[Pull Requests](https://github.com/AsBuiltReport/AsBuiltReport.NetApp.ONTAP/pulls) if this issue is already reported or fix has been created.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >-
        Please provide a detailed description of your idea so that the project maintainers and contributors can fully understand what change, feature, or improvement you are proposing.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: This field is optional. You may provide additional context for the idea you wish to propose. You may wish to include links to any related [issues](https://github.com/AsBuiltReport/AsBuiltReport.Microsoft.AD/issues) or other relevant information.
  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      description: >-
        Please ensure your change request fulfills all of the following requirements.
        If you are unsure of what a specific requirement means, please follow the links to learn about it and understand why it is necessary before submitting.
      options:
        - label: >-
            I have read [the documentation](https://www.asbuiltreport.com/user-guide/new-asbuiltconfig),
            and referred to the [known issues](https://www.asbuiltreport.com/user-guide/known-issues/) before submitting this change request.
          required: true
        - label: >-
            I have checked for previously opened & closed [issues](https://github.com/AsBuiltReport/AsBuiltReport.Microsoft.AD/issues) before submitting this change request.
          required: true
