name: Publish PowerShell Module

on:
  release:
    types: [published]

jobs:
  publish-to-gallery:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Set PSRepository to Trusted for PowerShell Gallery
        shell: pwsh
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
      - name: Install AsBuiltReport.Core module
        shell: pwsh
        run: |
          Install-Module -Name AsBuiltReport.Core -Repository PSGallery -Force
      - name: Install PSPKI module
        shell: pwsh
        run: |
          Install-Module -Name PSPKI -Repository PSGallery -Force
      - name: Install PSSharedGoods module
        shell: pwsh
        run: |
          Install-Module -Name PSSharedGoods -Repository PSGallery -Force
      - name: Test Module Manifest
        shell: pwsh
        run: |
          Test-ModuleManifest .\AsBuiltReport.Microsoft.AD.psd1
      - name: Publish module to PowerShell Gallery
        shell: pwsh
        run: |
          Publish-Module -Path ./ -NuGetApiKey ${{ secrets.PSGALLERY_API_KEY }} -Verbose
